# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true

# 定时发送时间 单位秒
time: 600

# 公告配置 (可自定义无限扩展多组,随机获取一组)
notice:
  # 第一组配置
  yi:
    - '&7--------------------------------------------'
    - '[服务器公告] 欢迎来到本服务器,希望你玩的愉快~'
    - '&7--------------------------------------------'
  # 第二组配置
  er:
    - '&7--------------------------------------------'
    - '[服务器公告] 可以使用时钟或者/mc打开菜单~'
    - '&7--------------------------------------------'